general_settings:
  master_key: "sk-sparkcore-local-dev"

model_list:
  - model_name: replicate-llama-3-8b
    litellm_params:
      model: replicate/meta/meta-llama-3-8b-instruct
      api_key: os.environ/REPLICATE_API_KEY
