app = "sparkcore-discord"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "../Dockerfile"

[processes]
  app = "npm run discord:gateway:worker"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
