import {
  SMOKE_ANTI_SUPPORTIVE_PREDICATES,
  SMOKE_DIRECT_SUPPORTIVE_PREDICATES,
  SMOKE_SOFT_SUPPORTIVE_PREDICATES
} from "@/lib/testing/smoke-short-supportive-predicate-groups";

export const SMOKE_SHORT_SUPPORTIVE_PREDICATES = [
  ...SMOKE_DIRECT_SUPPORTIVE_PREDICATES,
  ...SMOKE_SOFT_SUPPORTIVE_PREDICATES,
  ...SMOKE_ANTI_SUPPORTIVE_PREDICATES
] as const;
